#!/bin/sh
# This file is derived by the ldd3 load_hello by Rubini
#
# Author    :   William Simon <leonardo.suriano@live.it>
module="hasher"
device="hasher"
mode="666"
# Group: since distributions do it differently, look for wheel or use staff
if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi

# invoke insmod with all arguments we got
# and use a pathname, as insmod doesn't look in . by default
sudo /sbin/rmmod uio_pdrv_genirq
sudo /sbin/insmod ./$module.ko $* 
if [ $? -ne 0 ]
then
    exit $?
fi
# retrieve major number
major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
echo $major
# Remove stale nodes and replace them, then give gid and perms

sudo rm -f /dev/${device}
sudo mknod /dev/${device}0 c $major 0
sudo ln -sf ${device}0 /dev/${device}
sudo chgrp $group /dev/${device}
sudo chmod $mode  /dev/${device}
